#!/bin/bash

p() {

  # initialisation
  touch ~/.temp/ai
  unset output toLog
  input="$*"
  tokens=100
  temperature=1


  # cleaning input
  toLog=$(sed 's: \?\-t\?l\?c\?\ \?[0-9]*\.\?[0-9]* \?::g' <<< "$input")
  toLog=$(echo "Human:$toLog\nAI:")
  detectTemp=$(egrep -o "\-t [0-9]*.?[0-9]*" <<< "$input" \
  | egrep -o "[0-2].?[0-9]{0,2}")


  # analyse / format input
  if [[ "$input" == *"-s"* ]]; then
    tail -n 2 ~/.temp/ai >> ~/.temp/ai_saved
    return
  fi
  if [[ -n "$detectTemp" ]]; then
    temperature="$detectTemp"
  fi
  detectTokens=$(egrep -o "\-c [0-9]+" <<< "$input" | egrep -o "[0-9]+")
  if [[ -n "$detectTokens" ]]; then
    tokens="$detectTokens"
  fi
  detectLinesEmpty=$(egrep -o "\-l" <<< "$input")
  detectLines=$(egrep -o "\-l [0-9]+" <<< "$input")
  if [[ -n "$detectLinesEmpty" ]]; then
    if [[ -z "$detectLines" ]]; then detectLines=10; fi
    detectLines=$(echo "$(egrep -o '[0-9]+' <<< $detectLines)*2" | bc)
    input=$(cat ~/.temp/ai | tail -n "$detectLines" | sed -z 's:\n:\\n:g')
    input=$(echo "$input$toLog")
  else
    input=$(echo "$toLog")
  fi


  # send request / formatting output
  output=$(curl -s https://api.openai.com/v1/engines/text-davinci-001/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d '{
      "prompt": "'"$input"'",
      "temperature": '"$temperature"',
      "max_tokens": '"$tokens"',
      "top_p": 1,
      "frequency_penalty": 0,
      "presence_penalty": 0.6,
      "stop": [" Human:", " AI:"] }' \
    | grep -Po '\[{"text": ".+?(?=", "index)' \
    | sed 's:\[{"text"\: "::' \
    | sed 's:\\n::g' \
    | sed 's:^ *::' \
    | sed 's: *$::'\
  )

  # print results
  echo "$output" | fold -sw "$COLUMNS"
  printf "$toLog$output\n" >> ~/.temp/ai

}
