#!/bin/bash


# initialisation

PS1='\[\e[0;32m\]\w\[\e[0m\] '
printf '\e[6 q'

# aliases

alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias e='logout; exit'
alias vm='proot-distro login ubuntu'
alias a='nano ~/.bashrc; source ~/.bashrc'
alias s='source ~/.bashrc'
alias ccc='/bin/rm /data/data/com.termux/files/usr/tmp/* -rf'
alias u='apt update; apt upgrade; apt autoremove'
alias ls='ls --color --group-directories-first -t -X'
alias la='ls -A --color --group-directories-first -t -X'

# functions

ca() { bc <<< "$*"; }
sz() { du -sh "$1"; }
w() { chmod +x "$1"; }
cs() { cd "$1" && ls; }
ln() { cat "$1" | wc -l; }
apti() { apt install "$@"; }
path() { readlink -f "$1"; }
diff() { sort "$@" | uniq -u; }
uln() { sort "$1" | uniq -u | wc -l; }
print() { cat "$1" | fold -sw "$COLUMNS"; }
