#!/bin/bash


# initialisation

PS1='\[\e[0;32m\]\w\[\e[0m\] '
printf '\e[6 q'
export HISTSIZE=100000
export HISTFILESIZE=1000000
shopt -s histappend
export HISTCONTROL=ignoredups:erasedups
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
shopt -s checkwinsize
shopt -s globstar

# aliases

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias c='clear'
alias e='logout; exit'
alias dev='npm run dev'
alias deploy='npm run deploy'
alias vm='proot-distro login ubuntu'
alias a='nano ~/.bashrc; source ~/.bashrc'
alias s='source ~/.bashrc; source ~/.profile'
alias ccc='rm /data/data/com.termux/files/usr/tmp/* -rf'
alias u='apt update; apt upgrade; apt autoremove'
alias ls='ls --color --group-directories-first -t -X'
alias la='ls -A --color --group-directories-first -t -X'

# functions

ca() { bc <<< "$*"; }
sz() { du -sh "$1"; }
w() { chmod +x "$1"; }
cs() { cd "$1" && ls; }
ln() { cat "$1" | wc -l; }
apti() { apt install "$@"; }
path() { readlink -f "$1"; }
diff() { sort "$@" | uniq -u; }
uln() { sort "$1" | uniq -u | wc -l; }
print() { cat "$1" | fold -sw "$COLUMNS"; }
