#!/bin/bash

addsub() {

  if file -i "$1" | grep -q video; then
    video="$1"
  elif file -i "$2" | grep -q video; then
    video="$2"
  else
    echo 'No video found'
    return
  fi

  if [[ "$1" =~ ".srt" ]]; then
    subtitles="$1"
  elif [[ "$2" =~ ".srt" ]]; then
    subtitles="$2"
  else
    echo 'No subtitles found'
    return
  fi

  ffmpeg -i "$video" -i "$subtitles" -c copy -c:s mov_text -sub_charenc UTF-8 "${video:0:-4}-subs.mp4"

}

rec() {

  mkdir -p ~/Videos/ ~/Videos/Recorded

  resolution=(2540 1080)
  preset='-preset ultrafast'
  format='-pix_fmt yuv420p'
  fps='-framerate 30'
  lib='-c:v libx264'
  crf='-crf 30'
  gq='-qp 20'

  for ((i=0; i < ${#1}; i++)); do
    case "${1:$i:1}" in
      l) resolution=(1280 540); crf='-crf 35'; gq='-qp 10'; fps='-framerate 20'; echo low;;
      n) resolution=(2540 1080); crf='-crf 30'; gq='-qp 10'; fps='-framerate 30'; echo normal;;
      h) resolution=(3440 1440); crf='-crf 22'; gq='-qp 10'; fps='-framerate 60'; echo high;;
      s) preset='-preset slow'; echo slow;;
      e) echo efficient mode
         if [[ ! "$1" =~ 'g' ]]; then
           lib='-c:v libx265'
         fi;;
      g) if [[ "$1" =~ 'e' ]]; then
           lib='-codec:v hevc_vaapi'
         else
           lib='-codec:v h264_vaapi'
         fi
         lib+=" -vf 'scale=${resolution[0]}x${resolution[1]},hwdownload,format=nv12' -f mpegts"
#         lib+=" -vf 'deinterlace_vaapi=rate=field:auto=1,scale_vaapi=w=640:h=360,hwdownload,format=nv12' -f mpegts"
         device='-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi'
         echo 'enabled gpu acceleration';;
      *) echo
         echo 'Usage : rec <l/n/h + s? + e? + g?>'
         echo
         echo 'QUALITY : l=low / n=normal / h=high (default : normal)'
         echo 'ENCODING : e=efficient (default : compatibility)'
         echo 'ENCODING : g=enable gpu (default : CPU)'
         echo 'PRESET : s=slow (default : fast)'
         echo
         return;;
    esac
  done

  if [[ "$1" =~ 'g' ]]; then
    unset crf format preset resolution
  else
    resolution="-vf scale=${resolution[0]}:${resolution[1]}"
    unset gq device
  fi

  ffmpeg -hide_banner -stats -loglevel warning $device -f x11grab $fps -i :0 $resolution $lib $crf $gq $preset $format -y ~/Videos/Recorded/$(date +%y-%m-%d-%H:%M:%S).mp4
  echo "ffmpeg -hide_banner -stats -loglevel warning $device -f x11grab $fps -i :0 $resolution $lib $crf $gq $preset $format -y ~/Videos/Recorded/$(date +%y-%m-%d-%H:%M:%S).mp4"

}

# mkdir -p converted && readarray -t names <<< $(find -type f) && for ((i=0; i<${#names[@]}; i++)); do mv ${names[i]}-temp ffmpeg -i ${names[i]}-temp -q:v 5 -vf 'scale=if(gte(iw\,ih)\,min(2000\,iw)\,-2):if(lt(iw\,ih)\,min(2000\,ih)\,-2)' converted/$i.jpg; echo ${names[i]}; done

compressjpg() {

  echo
  args=($@)
  resolution=2000
  quality=4
  path=.
  unset marker destination
  for ((i=0; i < "${#args[@]}"; i++)); do
    if [[ "${args[i]}${args[i+1]}" =~ '-resolution'[0-9]+|'-R'[0-9]+ ]]; then
      resolution="${args[i+1]}"
    elif [[ "${args[i]}${args[i+1]}" =~ '-quality'[0-9]+|'-Q'[0-9]+ ]]; then
      quality="${args[i+1]}"
      if (("$quality" > 31)); then
        echo "Max quality is 31. Using this value."
        quality=31
      elif (("$quality" < 2)); then
        echo "Min quality is 2. Using this value."
        quality=2
      fi
    elif [[ "${args[i]}${args[i+1]}" =~ '-path'.+|'-P'.+ ]]; then
      path="${args[i+1]}"
      if [[ ! -d "$path" ]]; then
        echo -e "\e[31mERROR : Path does not exist.\e[0m"
        return
      fi
    elif [[ "${args[i]}${args[i+1]}" =~ '-destination'.+|'-D'.+ ]]; then
      destination="${args[i+1]}"
      if [[ "${destination: -1}" != '/' ]]; then
        destination="$destination/"
      fi
      if [[ ! -d "$destination" ]]; then
        echo -e '\e[33mWARNING : Destination does not exist.\e[0m'
        read -p "Do you want to create it ? > " answer
        if [[ "$answer" == 'y' ]]; then
          mkdir -p "$destination"
        else
          echo
          echo 'Abording...'
          echo
          return
        fi
      fi
    elif [[ "${args[i]}" =~ '-help'|'-H' ]]; then
      echo "USAGE : compressjpg <parameters>"
      echo
      echo 'Parameters :'
      echo '  --help (-H) : display this help message'
      echo '  --path (-P) : select input directory'
      echo '  --destination (-D) : select output directory'
      echo '  --quality (-Q) : specify jpg quality (2-31)'
      echo '  --resolution (-R) : downscale results'
      echo
      return
    fi
  done
  echo "R: $resolution - Q: $quality - P: $path - D: $destination"
  echo
  readarray -t files <<< $(find "$path" -type f | grep -v 'ffmpeg')
  if [[ -z "$destination" ]]; then
    marker="-ffmpeg"
  fi
  for ((i=0; i < "${#files[@]}"; i++)); do
    if [[ -n $(file -i "${files[i]}" | grep image) ]]; then
      outputName="${files[i]%.*}"
      if [[ "${outputName:0:2}" == './' ]]; then
        outputName="${outputName:2}"
      fi
      ffmpeg -loglevel error -y -i "${files[i]}" \
      -q:v "$quality" -preset placebo \
      -vf 'scale=if(gte(iw\,ih)\,min('"$resolution"'\,iw)\,-2):if(lt(iw\,ih)\,min('"$resolution"'\,ih)\,-2)' \
      "$destination${outputName##*/}$marker.jpg"
      echo -ne "\r$i/${#files[@]} "
    fi
  done
  echo -ne '\e[2K\r\e[32mDone\e[0m\n\n'

}
