#!/bin/bash


# url formatter/opener

url() {

  if [[ -z "$1" ]]; then
    echo "No input"
  fi
  if [[ ! "$1" =~ ^"http" ]]; then
    input=`echo https://"$1"`
  else
    input="$1"
  fi
  echo "$input"
  am start --user 0 -a android.intent.action.VIEW \
  -d "$input" > /dev/null

}

furl() {
  echo
  wget -S --spider "$1" 2>&1 | sed -En 's/^--[[:digit:]: -]{19}--  https?:\/\/(.*)/> \1\n/p'
}


# minecraft account checker

acc() {

  acc=(${1//:/ })
  request=$(curl -s -m 10 -H "Accept:application/json" -H "content-Type:application/json" 'https://authserver.mojang.com/authenticate' \
  -X POST --data '{"username": "'${acc[0]}'", "password": "'${acc[1]}'"}' | head -c 3)
  if [[ "$request" == "{\"c" ]]; then
    echo "> hit"
  else
    echo "> bad"
  fi

}

# googler

gg() {
  query=$(printf '%s' "$*" | tr ' ' '+' )
  lynx --cookies "https://www.google.com/search?q=$query"
}

# c compile + auto rename outout

cc() {
  name=$(echo "$1" | grep -Po '.*(?=\.)')
  clang "$1" -o "$name".exe
}

# get ip config

myip() {
  ip a | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort | uniq -u
}
