#!/bin/bash

d() {

  # initialisation
  unset files renamed
  mkdir -p .temp/ .temp/trash
  date=$(date +%m-%d+%H:%M:%S)
  files=("$@")

  # renamming and moving files
  for ((i=0; i < "${#files[@]}"; i++)); do
    renamed[i]=$(echo "$date-"$(basename -- "${files[i]}"))
    # echo "mv ${files[i]} ~/.temp/trash/${renamed[i]}"
    mv "${files[i]}" ~/.temp/trash/"${renamed[i]}" 2>/dev/null
  done

  # recap / analyse
  if [[ "$?" == 0 ]]; then
    if [[ "${#files[@]}" == 0 ]]; then
      echo "No elements were removed"
    elif [[ "${#files[@]}" == 1 ]]; then
      echo "Removed ${#files[@]} element"
    else
      echo "Moved ${#files[@]} elements to trash"
    fi
  else
    echo "Failed"
  fi

}
